### ISSUE TITLE
When attribute has multiple times the same rule, only the last one is validated

### ISSUE THREAD

**Issue by torrentalle** [proengsoft/laravel-jsvalidation#17]
When attribute has multiple times the same rule, only the last one is validated

In this case, for the attribute `distributor_city_id` the rule `required_if:type,distributor` **is not validated**

```php
$rules=[
     'distributor_city_id' => 'required_if:type,distributor|required_if:house,myhome',
     'distributor_name_id' => 'required_if:type,distributor',
     'type' => 'alpha',
     'house' => 'alpha',
];
```

**Comment by dennisoderwald** [comment]
+1

**Comment by dennisoderwald** [comment]
Issue not resolved :(

**Comment by torrentalle** [comment]
You have to publish the new Javascript files to apply the patches
```
php  artisan vendor:publish --provider="Proengsoft\JsValidation\JsValidationServiceProvider" --tag="public" --force
```

I'm preparing a new release with this bug an others solved,

**Comment by dennisoderwald** [comment]
I republished the new Javascript files - Bug is not resolved.. :(

**Comment by dennisoderwald** [comment]
@torrentalle: We release a new version today, can u help us?

**Comment by dennisoderwald** [comment]
We use `dev-master ac28943` - the bug already exists.

**Comment by torrentalle** [comment]
Did you republished Javascripts files after composer update?
Can you post your rules?  
I'm trying this case  and I'm getting correct results:

```
$rules=[
     'distributor_city_id' => 'required_if:type,distributor|required_if:house,myhome',
     'distributor_name_id' => 'required_if:type,distributor',
     'type' => 'alpha',
     'house' => 'alpha',
];
```

When field `house='myhome'` I get the error `The distributor city id field is required when house is myhome.`


When field `type='distributor'` I get the error `The distributor city id field is required when type is distributor.` and `The distributor name id field is required when type is distributor.`

**Comment by dennisoderwald** [comment]
@torrentalle: Do you use Skype to write directly?

**Comment by dennisoderwald** [comment]
Our rule-set:

````
        'payment_method'           => 'required|in:credit_card,sepa_debit',
        'credit_card_holder_name'  => 'required_if:payment_method,credit_card',
        'credit_card_no'           => 'required_if:payment_method,credit_card',
        'credit_card_expire_month' => 'required_if:payment_method,credit_card',
        'credit_card_expire_year'  => 'required_if:payment_method,credit_card',
        'credit_card_cvc'          => 'required_if:payment_method,credit_card',
```

**Comment by torrentalle** [comment]
The problem is related to radio buttons In dev-master this bug is fixed
May be other checks ar affected by the same bug. I will review the code

**Comment by torrentalle** [comment]
This bug is fixed in `master` branch

**Comment by denmarkamanodaya** [comment]
Issue still not resolved.
Having this issue right now and its 2017! <3
