### ISSUE TITLE
Validating input group

### ISSUE THREAD

**Issue by LocalHeroPro** [proengsoft/laravel-jsvalidation#765]
### Subject of the issue
When validating input group with Bootstrap 5, span is split to new line.

### Your environment
* version of this package: 4.5.1
* version of Laravel: 8.67.0

### Steps to reproduce
https://getbootstrap.com/docs/5.1/forms/input-group/
1. make form
```html
<div class="input-group mb-3">
  <input id="user_group-email" type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="basic-addon2">
  <span class="input-group-text" id="basic-addon2">@example.com</span>
</div>
```
2. click validate
3. we get that
```html
<div id="user_group-email-error" class="invalid-feedback">Some validation message</div>
```
between input and span against on end .input-group. 

### Expected behaviour
Validation message have to go on end of `.input-group` class.
![image](https://user-images.githubusercontent.com/42643563/138568860-f993df5b-ced8-45c9-aff8-5c6e20078f87.png)

### Actual behaviour
Validation message go after input, but before span.
Before validation 
![image](https://user-images.githubusercontent.com/42643563/138568834-7b242994-5d80-4b88-ba13-b969d29757ae.png)
After validation
![image](https://user-images.githubusercontent.com/42643563/138568820-3013a94a-e3a2-4c82-b474-90bb76b1b432.png)

**Comment by mankowitz** [comment]
In the bootstrap4 view, this was addressed. Would it make sense to copy that part?

**Comment by bytestream** [comment]
@mankowitz I'm not sure what fix you're referring to in bootstrap4, but sure :)

**Comment by LocalHeroPro** [comment]
I think "issue" still exists:
![image](https://user-images.githubusercontent.com/42643563/201475701-41bdb64c-7d45-4f74-ab38-5dfa714ebb8f.png)
